### ISSUE TITLE
it doesn't import in Google Colab

### ISSUE THREAD

**Issue by rezadarooei** [kiraving/SegGradCAM#2]
Hello dear Kira
I'm working on your seg_grad cam code but unfortunately when I want to import Seggradcam libraries it doesn't work, I face this error:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-2ab021869574> in <module>()
----> 1 import seggradcam.metrics

3 frames
/usr/local/lib/python3.7/dist-packages/keras/backend.py in <module>()
     35 from tensorflow.python.distribute import distribute_coordinator as dc
     36 from tensorflow.python.distribute import distribute_coordinator_context as dc_context
---> 37 from tensorflow.python.eager.context import get_config
     38 from tensorflow.python.framework import config
     39 from keras import backend_config

ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`
DO you have any idea?
Thanks

**Comment by rezadarooei** [comment]
I get it please instead of using from keras import backend as K
use :
` from tensorflow.keras import backend as K `

**Comment by kiraving** [comment]
@rezadarooei we might have different tensorflow versions. I didn't test the code in Colab.
