### ISSUE TITLE
Tensorflow2

### ISSUE THREAD

**Issue by sbradshaw877** [kiraving/SegGradCAM#3]
Hi, 

Do you have any plans to update this repository to Tensorflow 2? I am working with your SegGradCAM code for explainable AI, but my modifications to  allow for use of Tensorflow 2 have not been successful yet (since my model is built in Tensorflow 2). So far I have found the main difference to be how the gradients are computed (GradientTape() vs gradient()). Thanks!

**Comment by kiraving** [comment]
Hi,
No, sorry, it's not on my plan.
