### ISSUE TITLE
gradcam and segmentation output

### ISSUE THREAD

**Issue by soans1994** [kiraving/SegGradCAM#5]
hello author,

I have a question related to grad cam. I want to know the difference between class activation maps and output feature map. If i apply the gradcam module for the last conv block or intermediate conv blocks, it is supposed to give the heatmap about where in the image the channels are activated. In case of classification task it maskes sense. What about in case of segmentation task? 
If i apply grad cam to the last conv block, the gradcam heatmap is same as the output feature map or output segmentation output?
I have tried this on my task, and i found that the gradcam heatmap and final output is different. What can i conclude from this?

![5](https://user-images.githubusercontent.com/30766648/145819468-3e42e309-7d33-4fda-856d-176a4a4cd8e5.png)
![3](https://user-images.githubusercontent.com/30766648/145819473-569af398-fbbb-4032-86b5-9294772fc92e.png)

thank you

**Comment by kiraving** [comment]
I can't draw any conclusion from the heatmaps with seen the original image. 
If the heatmap (gradients taken with respect to the bottleneck) doesn't repeat the segmentation mask, it means the context influenced the prediction of the mask.
