### ISSUE TITLE
IndexError: index 128 is out of bounds for axis 0 with size 128

### ISSUE THREAD

**Issue by iftiben10** [kiraving/SegGradCAM#6]
### **Hello,** 
When I run SegGradCam code to use GradCam in Thresholding Segmentation with PixelRoI, 
an unexpected error occurs:
##### **Code:**

> from imageio import imread
> image = imread("../input/retinal-vessel-segmentation/DRIVE/training/images/21_training.tif")
> image = tf.image.resize(images=image, size=[128, 128])
> image = image.numpy()
> image = image.astype(np.uint8)
> data = Image.fromarray(image)
> data.save('dummy_pic.jpg')
> ##
> a = "./dummy_pic.jpg"
> a = imread(a)
> ##
> roi=PixelRoI(128,128,a)
##### **Error:**
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_35/845604040.py in <module>
      1 # image = imread(images[0], 3)
----> 2 roi=PixelRoI(128,128,a)
      3 # roi.shape()

/tmp/ipykernel_35/2143735659.py in __init__(self, i, j, image)
     64         self.image = image
     65         self.roi = np.zeros((image.shape[-3], image.shape[-2]))
---> 66         self.roi[i, j] = 1
     67         self.i = i
     68         self.j = j

IndexError: index 128 is out of bounds for axis 0 with size 128
```
#### Environment:
Desktop         : Virtual Environment Kaggle, GPU
Tensorflow     : 2.6.2 (unupgradable)
Matplotib        : 3.5.1 (unupgradable)

#### Question:
Can anyone please help me to solve this error?

**Comment by kiraving** [comment]
I would try index 127. If the size of the axis is 128, it means there are indexes from 0 to 127
